#!/bin/bash

set -euo pipefail

# Define the location of the network scanning script inside the Docker container
NETWORK_SCANNING_SCRIPT="/usr/share/filebeat/network-json.sh"

# Run the network scanning script in the background
echo "Running network scanning script..."
/bin/bash "$NETWORK_SCANNING_SCRIPT" -r "${NETWORK_RANGE}" -p "${PARALLELISM}" -v "${VERBOSE}" -l "${LOCATION}" &

# Check if the user has invoked the image with flags.
# e.g., "filebeat -c filebeat.yml"
if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]]; then
  exec filebeat "$@"
else
  # They may be looking for a Beat subcommand, like "filebeat setup".
  subcommands=$(filebeat help |
    awk 'BEGIN {RS=""; FS="\n"} /Available Commands:/' |
    awk '/^\s+/ {print $1}')

  # If we _did_ get a subcommand, pass it to filebeat.
  for subcommand in $subcommands; do
    if [[ $1 == $subcommand ]]; then
      exec filebeat "$@"
    fi
  done
fi

# If neither of those worked, then they have specified the binary they want,
# so just do exactly as they say.
exec "$@"
